# Generated by Django 3.2.7 on 2021-09-07 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=64)),
                ('itemDescription', models.CharField(max_length=256)),
                ('itemPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('itemActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='itemCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemCartItems', models.ManyToManyField(related_name='orderitems', to='voleybotapp.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderCompleted', models.BooleanField(default=False)),
                ('orderCancelled', models.BooleanField(default=False)),
                ('orderTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('userCurrentTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('userCurrentOrders', models.ManyToManyField(related_name='orderer', to='voleybotapp.Order')),
                ('userItemCart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voleybotapp.itemcart')),
            ],
        ),
        migrations.CreateModel(
            name='scanCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanCodeValue', models.CharField(max_length=64)),
                ('scanCodeFile', models.IntegerField()),
                ('scanCodeRelatedItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voleybotapp.item')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='orderEr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voleybotapp.user'),
        ),
        migrations.AddField(
            model_name='order',
            name='orderItems',
            field=models.ManyToManyField(related_name='items', to='voleybotapp.Item'),
        ),
        migrations.AddField(
            model_name='itemcart',
            name='itemCartUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voleybotapp.user'),
        ),
        migrations.AddField(
            model_name='item',
            name='itemCurrentlyInCarts',
            field=models.ManyToManyField(related_name='carts', to='voleybotapp.itemCart'),
        ),
        migrations.AddField(
            model_name='item',
            name='itemScanCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voleybotapp.scancode'),
        ),
    ]
