# Generated by Django 3.2.7 on 2021-09-08 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0002_auto_20210908_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scancode',
            name='scanCodeFile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scancode',
            name='scanCodeRelatedItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voleybotapp.item'),
        ),
        migrations.AlterField(
            model_name='scancode',
            name='scanCodeValue',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
