# Generated by Django 3.2.7 on 2021-09-09 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0003_auto_20210908_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcart',
            old_name='itemCartUser',
            new_name='relatedTo',
        ),
        migrations.RemoveField(
            model_name='itemcart',
            name='itemCartItems',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userCurrentOrders',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userCurrentTotal',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userItemCart',
        ),
        migrations.AddField(
            model_name='itemcart',
            name='currentCartTotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=64),
        ),
        migrations.AddField(
            model_name='itemcart',
            name='items',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='user',
            name='itemCart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voleybotapp.itemcart'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='orders',
            field=models.ManyToManyField(related_name='ordersofuser', to='voleybotapp.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderItems',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='voleybotapp.itemcart'),
        ),
    ]
