# Generated by Django 3.2.7 on 2021-09-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0004_auto_20210909_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemCurrentlyInCarts',
            new_name='currentlyIn',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemActive',
            new_name='isActive',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemPrice',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='itemDescription',
        ),
        migrations.RemoveField(
            model_name='item',
            name='itemName',
        ),
        migrations.RemoveField(
            model_name='item',
            name='itemScanCode',
        ),
        migrations.AddField(
            model_name='item',
            name='QRCodeValue',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='item',
            name='group',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.DeleteModel(
            name='scanCode',
        ),
    ]
