# Generated by Django 3.2.7 on 2021-09-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0005_auto_20210909_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcart',
            old_name='currentCartTotal',
            new_name='currentTotal',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='orderCancelled',
            new_name='cancelled',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='orderCompleted',
            new_name='completed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderItems',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderTotal',
        ),
        migrations.AddField(
            model_name='menu',
            name='groups',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=64),
        ),
    ]
