# Generated by Django 3.2.7 on 2021-09-09 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0006_auto_20210909_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='currentlyIn',
        ),
        migrations.RemoveField(
            model_name='user',
            name='orders',
        ),
        migrations.AlterField(
            model_name='item',
            name='group',
            field=models.CharField(default=' ', max_length=128),
        ),
        migrations.CreateModel(
            name='ItemInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voleybotapp.itemcart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voleybotapp.item')),
            ],
        ),
    ]
