# Generated by Django 3.2.7 on 2021-09-10 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0007_auto_20210909_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcart',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
