# Generated by Django 3.2.7 on 2021-09-11 22:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0011_auto_20210911_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mode',
            field=models.CharField(default='null', max_length=256),
        ),
    ]
