# Generated by Django 3.2.7 on 2021-09-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0012_auto_20210912_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='groups',
            field=models.CharField(default='', max_length=2048, null=True),
        ),
    ]
