# Generated by Django 3.2.8 on 2021-10-30 15:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0013_alter_menu_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belongs_type', models.CharField(max_length=128)),
                ('belongs_id', models.IntegerField()),
                ('items', models.CharField(max_length=128)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('cart_id', models.IntegerField(unique=True)),
                ('orders_ids', models.CharField(max_length=5096, unique=True)),
                ('language_code', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('level', models.IntegerField(unique=True)),
                ('items_ids', models.CharField(blank=True, max_length=5096)),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_value', models.CharField(max_length=128, unique=True)),
                ('image_address', models.CharField(max_length=128, unique=True)),
                ('item_id', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='itemcart',
            name='relatedTo',
        ),
        migrations.RemoveField(
            model_name='itemincart',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='itemincart',
            name='item',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.RemoveField(
            model_name='user',
            name='itemCart',
        ),
        migrations.RemoveField(
            model_name='item',
            name='QRCodeValue',
        ),
        migrations.RemoveField(
            model_name='item',
            name='group',
        ),
        migrations.RemoveField(
            model_name='item',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderEr',
        ),
        migrations.AddField(
            model_name='item',
            name='group_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='group_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='in_carts_ids',
            field=models.CharField(blank=True, max_length=5096),
        ),
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='qrcode_id',
            field=models.IntegerField(default='1', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='cart_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='orderer_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 15, 44, 32, 20642, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='In progress', max_length=128),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='itemCart',
        ),
        migrations.DeleteModel(
            name='ItemInCart',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
