# Generated by Django 3.2.8 on 2021-10-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0014_auto_20211030_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_id', models.IntegerField()),
                ('on_press_action', models.CharField(max_length=5096)),
            ],
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_x', models.IntegerField()),
                ('buttons', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation_string', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='TelUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_db_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TextString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_id', models.IntegerField()),
                ('lang_id', models.IntegerField()),
                ('text', models.CharField(max_length=5096)),
            ],
        ),
    ]
