# Generated by Django 3.2.8 on 2021-10-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0015_button_keyboard_language_teluser_textstring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cart_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='orders_ids',
            field=models.CharField(max_length=5096),
        ),
        migrations.AlterField(
            model_name='item',
            name='qrcode_id',
            field=models.IntegerField(),
        ),
    ]
