# Generated by Django 3.2.8 on 2021-10-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0016_auto_20211031_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo_address',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
