# Generated by Django 3.2.8 on 2021-10-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0017_item_photo_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='teluser',
            name='tel_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teluser',
            name='core_db_id',
            field=models.IntegerField(unique=True),
        ),
    ]
