# Generated by Django 3.2.8 on 2021-10-31 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0019_alter_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cart_id',
            field=models.IntegerField(default=1),
        ),
    ]
