# Generated by Django 3.2.8 on 2021-11-01 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0021_auto_20211101_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='presentation_string',
            new_name='code',
        ),
    ]
