# Generated by Django 3.2.8 on 2021-11-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0022_rename_presentation_string_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyboard',
            name='on_init_action',
            field=models.CharField(blank=True, max_length=5096),
        ),
        migrations.AlterField(
            model_name='button',
            name='label_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='button',
            name='on_press_action',
            field=models.CharField(blank=True, max_length=5096),
        ),
        migrations.AlterField(
            model_name='cart',
            name='belongs_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='belongs_type',
            field=models.CharField(default='Customer', max_length=128),
        ),
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='customer',
            name='language_code',
            field=models.CharField(default='1', max_length=128),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='layout_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(default='uk', max_length=512),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Getting ready', max_length=128),
        ),
        migrations.AlterField(
            model_name='textstring',
            name='lang_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='textstring',
            name='str_id',
            field=models.IntegerField(default=1),
        ),
    ]
