# Generated by Django 3.2.7 on 2021-11-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0024_auto_20211103_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='on_press_action',
            field=models.TextField(blank=True, max_length=5096),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='on_init_action',
            field=models.TextField(blank=True, max_length=5096),
        ),
    ]
