# Generated by Django 3.2.7 on 2021-11-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0025_auto_20211103_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyboard',
            name='label_id',
            field=models.IntegerField(default=1),
        ),
    ]
