# Generated by Django 3.2.7 on 2021-11-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0026_keyboard_label_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='photo_address',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='image_address',
        ),
        migrations.AddField(
            model_name='item',
            name='image_path',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
