# Generated by Django 3.2.7 on 2021-11-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0027_auto_20211106_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='image_path',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
