# Generated by Django 3.2.7 on 2021-11-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0028_qrcode_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcode',
            old_name='code_value',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='item',
            name='group_id',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
