# Generated by Django 3.2.7 on 2021-11-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0029_auto_20211107_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='item_id',
            field=models.CharField(max_length=128),
        ),
    ]
