# Generated by Django 3.2.7 on 2021-11-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0030_alter_qrcode_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
