# Generated by Django 3.2.7 on 2021-11-10 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0031_alter_group_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyboard',
            old_name='one_time_keyboard',
            new_name='flush_chat',
        ),
    ]
