# Generated by Django 3.2.7 on 2021-11-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0032_rename_one_time_keyboard_keyboard_flush_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='teluser',
            name='message_history',
            field=models.CharField(blank=True, max_length=65536),
        ),
    ]
