# Generated by Django 3.2.7 on 2021-11-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0033_teluser_message_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='items',
            new_name='items_ids',
        ),
        migrations.RemoveField(
            model_name='item',
            name='in_carts_ids',
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
