# Generated by Django 3.2.7 on 2021-11-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0034_auto_20211111_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
