# Generated by Django 3.2.7 on 2021-11-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0035_customer_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderer_id',
            field=models.IntegerField(default=1),
        ),
    ]
