# Generated by Django 3.2.7 on 2021-11-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0036_alter_order_orderer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items_ids',
            field=models.CharField(default=';', max_length=128),
        ),
        migrations.AlterField(
            model_name='customer',
            name='orders_ids',
            field=models.CharField(default=';', max_length=5096),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart_id',
            field=models.IntegerField(default=1),
        ),
    ]
