# Generated by Django 3.2.7 on 2021-11-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0037_auto_20211112_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Being prepared', max_length=128),
        ),
    ]
