# Generated by Django 3.2.7 on 2021-11-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0039_teluser_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teluser',
            name='qr_code',
            field=models.IntegerField(default=0),
        ),
    ]
