# Generated by Django 3.2.7 on 2021-11-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleybotapp', '0040_alter_teluser_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('belongs_to', models.IntegerField(blank=True, default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='addons_ids',
            field=models.CharField(default=';', max_length=1024),
        ),
    ]
